[versions]
agp = "8.4.1"
kotlin = "2.0.21"
composeBom = "2024.05.00"
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.8.0"
activityCompose = "1.9.0"
googleServices = "4.4.1"
firebaseBom = "33.1.0"
room = "2.6.1"
navigationCompose = "2.7.7"
sqliteKtx = "2.4.0"

[libraries]
# AndroidX & Compose
androidx-core-ktx = { group="androidx.core", name="core-ktx", version.ref="coreKtx" }
androidx-lifecycle-runtime-ktx = { group="androidx.lifecycle", name="lifecycle-runtime-ktx", version.ref="lifecycleRuntimeKtx" }
androidx-activity-compose = { group="androidx.activity", name="activity-compose", version.ref="activityCompose" }
androidx-compose-bom = { group="androidx.compose", name="compose-bom", version.ref="composeBom" }
androidx-ui = { group="androidx.compose.ui", name="ui" }
androidx-ui-graphics = { group="androidx.compose.ui", name="ui-graphics" }
androidx-ui-tooling-preview = { group="androidx.compose.ui", name="ui-tooling-preview" }
androidx-material3 = { group="androidx.compose.material3", name="material3" }

# Firebase
firebase-bom = { group="com.google.firebase", name="firebase-bom", version.ref="firebaseBom" }
firebase-auth = { group="com.google.firebase", name="firebase-auth" }
firebase-firestore = { group="com.google.firebase", name="firebase-firestore" }

# Room
room-runtime = { group="androidx.room", name="room-runtime", version.ref="room" }
room-ktx = { group="androidx.room", name="room-ktx", version.ref="room" }
room-compiler = { group="androidx.room", name="room-compiler", version.ref="room" }
androidx-sqlite-ktx = { group="androidx.sqlite", name="sqlite-ktx", version.ref="sqliteKtx" }

# Navigation
navigation-compose = { group="androidx.navigation", name="navigation-compose", version.ref="navigationCompose" }

[plugins]
android-application = { id="com.android.application", version.ref="agp" }
kotlin-android = { id="org.jetbrains.kotlin.android", version.ref="kotlin" }
kotlin-compose-compiler = { id="org.jetbrains.kotlin.plugin.compose", version.ref="kotlin" }
google-services = { id="com.google.gms.google-services", version.ref="googleServices" }
